# Generated by Django 5.0.1 on 2024-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nxapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="img",
            field=models.ImageField(default="hihi", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
